//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerWarehouses.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyShoeStoreEntities : DbContext
    {
        public MyShoeStoreEntities()
            : base("name=MyShoeStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Export> Export { get; set; }
        public virtual DbSet<Import> Import { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<ModelShoes> ModelShoes { get; set; }
        public virtual DbSet<Shoes> Shoes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeShoe> TypeShoe { get; set; }
    }
}
