//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerWarehouses.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelShoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelShoes()
        {
            this.Shoes = new HashSet<Shoes>();
        }
    
        public long ModelShoes_ID { get; set; }
        public string NameShoese { get; set; }
        public int TypeID { get; set; }
        public int CompanyID { get; set; }
        public byte Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual TypeShoe TypeShoe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shoes> Shoes { get; set; }
    }
}
